# Generated by Django 5.1.2 on 2025-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_newstudent_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='age',
            field=models.IntegerField(),
        ),
    ]
